### ISSUE TITLE
利用vue实现一个抽屉的动画

### ISSUE THREAD

**Issue by AILINGANGEL** [AILINGANGEL/VueLearn#6]
### 核心
使用vue的过渡动画

```html
        <transition name="slide">
            <your-component></your-component>
        </transition>
```

```css
.slide-leave-active,
.slide-enter-active {
    transition: 1s;
}
/*进入过渡的开始状态*/
.slide-enter {
    transform: translate(100%, 0);
}
/*离开过渡的结束状态*/
.slide-leave-to {
    transform: translate(100%, 0);
}
```
v-enter和v-leave-to的状态一样可以确保组件从哪里来回哪里去
